drop schema blackjack;
create schema blackjack;
use blackjack;
insert into cartas(
carta_jugador,
    simbolo,
    palo,
    valor,
    url
)
values (false,'2','CORAZON',2,'../../assets/corazon_2.png'),(false,'3','CORAZON',3,'../../assets/corazon_3.png'),(false,'4','CORAZON',4,'../../assets/corazon_4.png'),(false,'5','CORAZON',5,'../../assets/corazon_5.png'),(false,'6','CORAZON',6,'../../assets/corazon_6.png'),(false,'7','CORAZON',7,'../../assets/corazon_7.png'),(false,'8','CORAZON',8,'../../assets/corazon_8.png'),(false,'9','CORAZON',9,'../../assets/corazon_9.png'),(false,'10','CORAZON',10,'../../assets/corazon_10.png'),(false,'J','CORAZON',10,'../../assets/corazon_j.png'),(false,'Q','CORAZON',10,'../../assets/corazon_q.png'),(false,'K','CORAZON',10,'../../assets/corazon_k.png'),(false,'A','CORAZON',1,'../../assets/corazon_a.png'),(false,'2','PICA',2,'../../assets/pica_2.png'),(false,'3','PICA',3,'../../assets/pica_3.png'),(false,'4','PICA',4,'../../assets/pica_4.png'),(false,'5','PICA',5,'../../assets/pica_5.png'),(false,'6','PICA',6,'../../assets/pica_6.png'),(false,'7','PICA',7,'../../assets/pica_7.png'),(false,'8','PICA',8,'../../assets/pica_8.png'),(false,'9','PICA',9,'../../assets/pica_9.png'),(false,'10','PICA',10,'../../assets/pica_10.png'),(false,'J','PICA',10,'../../assets/pica_j.png'),(false,'Q','PICA',10,'../../assets/pica_q.png'),(false,'K','PICA',10,'../../assets/pica_k.png'),(false,'A','PICA',1,'../../assets/pica_a.png'),(false,'2','DIAMANTE',2,'../../assets/diamante_2.png'),(false,'3','DIAMANTE',3,'../../assets/diamante_3.png'),(false,'4','DIAMANTE',4,'../../assets/diamante_4.png'),(false,'5','DIAMANTE',5,'../../assets/diamante_5.png'),(false,'6','DIAMANTE',6,'../../assets/diamante_6.png'),(false,'7','DIAMANTE',7,'../../assets/diamante_7.png'),(false,'8','DIAMANTE',8,'../../assets/diamante_8.png'),(false,'9','DIAMANTE',9,'../../assets/diamante_9.png'),(false,'10','DIAMANTE',10,'../../assets/diamante_10.png'),(false,'J','DIAMANTE',10,'../../assets/diamante_j.png'),(false,'Q','DIAMANTE',10,'../../assets/diamante_q.png'),(false,'K','DIAMANTE',10,'../../assets/diamante_k.png'),(false,'A','DIAMANTE',1,'../../assets/diamante_a.png'),(false,'2','TREBOL',2,'../../assets/trebol_2.png'),(false,'3','TREBOL',3,'../../assets/trebol_3.png'),(false,'4','TREBOL',4,'../../assets/trebol_4.png'),(false,'5','TREBOL',5,'../../assets/trebol_5.png'),(false,'6','TREBOL',6,'../../assets/trebol_6.png'),(false,'7','TREBOL',7,'../../assets/trebol_7.png'),(false,'8','TREBOL',8,'../../assets/trebol_8.png'),(false,'9','TREBOL',9,'../../assets/trebol_9.png'),(false,'10','TREBOL',10,'../../assets/trebol_10.png'),(false,'J','TREBOL',10,'../../assets/trebol_j.png'),(false,'Q','TREBOL',10,'../../assets/trebol_q.png'),(false,'K','TREBOL',10,'../../assets/trebol_k.png'),(false,'A','TREBOL',1,'../../assets/trebol_a.png');
select * from jugadores;